# Generated by Django 5.0.6 on 2024-05-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0002_rename_user_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
